version: "3.9"
services:
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    command: npx serve -s dist
    ports:
      - "3000:3000"
